###GET ONE OBJECT
GET http://localhost:3000/api/pizza/2
Content-Type:application/json

###GET ALL PIZZAZ
GET http://localhost:3000/api/pizza
Content-Type: application/json

###POST ocean pizza
POST http://localhost:3000/api/pizza
Content-Type:application/json

{
    "name":"ocean pizza",
    "filling":"tuna",
    "size":"small"
}
### PUT PIZZA
PUT http://localhost:3000/api/pizza/2
Content-Type: application/json

{
    "name":"pizza two",
    "filling":"pommes",
    "size":"gigantic"
}

###DELETE HAWAII
DELETE http://localhost:3000/api/pizza/2
Content-Type: application/json